# -*- coding: utf-8 -*-
"""Trabalho1Estatistica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqpgxLTA-Y1uK-DJV5RVxpiYoKcZRniV
"""

import pandas as pd

df = pd.read_excel("/content/Modelo_Relatorio-Fichamento_[AVA1]_T1_2026.1(1).xlsx",sheet_name="BaseAnalisada")

pd.set_option('display.max_rows', None) # Set to None to display all rows, or an integer for a specific number

"""#Qualidade dos Dados"""

#Existem Dados Faltantes na base?
#Python considerou a categoria None como um valor nulo
df['ParentalEducationText'] = df['ParentalEducationText'].fillna('None')
df['ParentalSupportText'] = df['ParentalSupportText'].fillna('None')
parentalEducationText = df[df["ParentalEducationText"].isnull()==True]
df.drop(columns=['StudentID'],inplace=True)
df.info()

"""#Estatistica Descritiva

##Medidas de Posição

##Função para Medidas de Posição
"""

#Algoritmo da função

'''
Inicio Algoritmo
  ler a base de dados
  criar dois vetores : um pra dados qualitativos e outro pra dados quantitativos
  iterar sobre a base e classificar cada coluna como quantitativa ou qualitativa, passando o nome pro vetor correspondente

  funcao 1: dados qualitativos
    recebe como parametro : base de dados e vetor com nome das colunas de dados qualitativos

    calcula para cada coluna:
        medidas de posicao :
            moda unimodal
            frequencia da moda unimodal
            moda multimodal
            frequencia da moda multimodal
        medidas de dispersao:
            RV : razao de variacao = 1 - (frequencia da moda / n total de observacoes)
                quanto mais proximos de 1, mais dispersos.

    retorna um dicionario contendo todas as medidas de posicao de dados qualitativos

  funcao 2 : dados quantitativos
    recebe como parametro : base de dados e vetor com nome das colunas de dados quantitativos

    calcula para cada coluna:
        medida de posicao :
            media aritmetica simples np.mean()
            media aritmetica aparada : trim_mean(base,0.10)
            mediana = np.median()
        medida de dispercao :
            Minimo
            Maximo
            Amplitude
            Variancia Amostral
            Desvio Padrao Amostral
            CV (Coeficiente de Variacao)
                ate 15% : variacao pequena
                entre 15% e 30% : variacao media
                maior que 30% : variacao grande

    retorna um dicionario contendo todas as medidas de posicao de dados quantitativos
'''

import statistics
import numpy as np
from scipy.stats import trim_mean

#criar dois vetores : um pra dados qualitativos e outro pra dados quantitativos
colunas_qualitativas = []
colunas_quantitativas = []

#iterar sobre a base e classificar cada coluna como quantitativa ou qualitativa, passando o nome pro vetor correspondente
def classifica_tipos_dados(base : pd.DataFrame, vetorColunasQualitativas : list, vetorColunasQuantitativas : list) :
  for coluna in range(0,base.shape[1]):
    aux = pd.array(base.iloc[:,coluna])
    nome_coluna = base.columns[coluna]
    if aux.dtype in (
        'float16', 'float32', 'float64', 'float128',
        'int8', 'int16', 'int32', 'int64',
        'uint8', 'uint16', 'uint32', 'np.uint64'):
      if nome_coluna not in vetorColunasQuantitativas:
        vetorColunasQuantitativas.append(nome_coluna)
    else :
      if nome_coluna not in vetorColunasQualitativas:
        vetorColunasQualitativas.append(nome_coluna)

def descreve_variavel(base : pd.DataFrame, variavel : str, vetorColunasQualitativas, vetorColunasQuantitativas) -> dict:

  colunaVariavel = base[variavel]
  descricao_variavel_qualitativa = dict()
  descricao_variavel_quantitativa = dict()

  if variavel in vetorColunasQuantitativas:
    descricao_variavel_quantitativa["nome"] = variavel
    descricao_variavel_quantitativa["tipo"] = 'Quantitativa'
    descricao_variavel_quantitativa["media aritmetica simples"] = np.nanmean(colunaVariavel)
    descricao_variavel_quantitativa["media aritmetica aparada"] = trim_mean(colunaVariavel,0.10)
    descricao_variavel_quantitativa["mediana"] = np.nanmedian(colunaVariavel)
    descricao_variavel_quantitativa["minimo"] = int(np.nanmin(colunaVariavel))
    descricao_variavel_quantitativa["maximo"] = int(np.nanmax(colunaVariavel))
    descricao_variavel_quantitativa["amplitude"] = descricao_variavel_quantitativa['maximo'] - descricao_variavel_quantitativa['minimo']
    descricao_variavel_quantitativa["variancia amostral"] = np.nanvar(colunaVariavel, ddof=1)
    descricao_variavel_quantitativa["desvio padrao amostral"] = np.nanstd(colunaVariavel, ddof=1)
    descricao_variavel_quantitativa["cv"] = (descricao_variavel_quantitativa["desvio padrao amostral"])/descricao_variavel_quantitativa['media aritmetica simples']*100
    return descricao_variavel_quantitativa
  elif variavel in vetorColunasQualitativas:
    descricao_variavel_qualitativa["nome"] = variavel
    descricao_variavel_qualitativa["tipo"] = 'Qualitativa'
    descricao_variavel_qualitativa["moda unimodal"] = statistics.mode(colunaVariavel)
    descricao_variavel_qualitativa["frequencia da moda unimodal"] = colunaVariavel.value_counts().get(descricao_variavel_qualitativa['moda unimodal'], 0)
    descricao_variavel_qualitativa["moda multimodal"] = statistics.multimode(colunaVariavel)
    descricao_variavel_qualitativa["rv"] = 1 - (descricao_variavel_qualitativa['frequencia da moda unimodal']/len(colunaVariavel))
    return descricao_variavel_qualitativa

def get_all_variables_desc(base : pd.DataFrame, vetorColunasQualitativas : list, vetorColunasQuantitativas : list) -> list:
  lista_de_descricoes_das_variaveis = []
  for variavel in base:
    lista_de_descricoes_das_variaveis.append(descreve_variavel(base,variavel, colunas_qualitativas, colunas_quantitativas))
  return lista_de_descricoes_das_variaveis

"""#MAIN"""

classifica_tipos_dados(df,colunas_qualitativas,colunas_quantitativas)
display(pd.DataFrame(get_all_variables_desc(df, colunas_qualitativas, colunas_quantitativas)))